const fs=require('fs'),path=require('path');
const p=path.join(__dirname,'assets','models','room_emo_colliders.json');
const d=JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,''));
d.lightmaps={on:'room_lm_on.jpg',off:'room_lm_off.jpg'};
d.lightmapsMobile={on:'room_lm_on_2k.jpg',off:'room_lm_off_2k.jpg'};
d.backdrop='backdrop_yard.jpg';
d.backdropMobile='backdrop_yard_1k.jpg';
fs.writeFileSync(p,JSON.stringify(d,null,1),{encoding:'utf8'});
console.log('десктоп :',d.lightmaps.on,'+',d.backdrop);
console.log('мобилка :',d.lightmapsMobile.on,'+',d.backdropMobile);
